### ISSUE TITLE
Multi-variate analysis

### ISSUE THREAD

**Issue by charlesopara** [ajw2329/junctionCounts#13]
Is multi-variate analysis enabled with this version of the tool?

**Comment by ajw2329** [comment]
Hi Charles -- thanks for your interest in the tool.  Currently it doesn't directly support formal multivariate analysis -- we'll look into doing so in the future.  In the meantime, you might be able to change some code in [DEXSeq_comparison.R](https://github.com/ajw2329/junctionCounts/blob/master/junctionCounts/DEXSeq_comparison.R) (at least line 79) since it is calling DEXseq and it looks like DEXseq itself [supports multi-factor analysis](https://support.bioconductor.org/p/64546/).  If your analysis doesn't boil down to comparing condition A vs B while blocking on others, though, some more extensive modification might be needed.  What do you think @ajritter8 ?

**Comment by charlesopara** [comment]
That is a great idea! That should work. I'll give it a try and let you know.
Thank you so much!
